version: '3.7'

services:
  mysql:
    container_name: movies3-mysql
    image: movies3-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # schema?
    networks:
      - movies3-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: movies3-app
    image: movies3-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - movies3-network

networks:
  movies3-network: